### ISSUE TITLE
Windows releas

### ISSUE THREAD

**Issue by EffeF** [nvllsvm/emby-unlocked#1]
Would it also be possible to have the .exe file to install on Windows systems?

**Comment by schoerg** [comment]
From the official readme:

```
* Open a PowerShell console.
* Go to Tools\Windows_Build_Scripts
* Run: .\MediaBrowser.Build.ps1
```

**Comment by EffeF** [comment]
Someone built the Windows version? Is there hope for a release for Windows systems?

**Comment by schoerg** [comment]
See my comment above.

**Comment by EffeF** [comment]
Yes, I see it... but I do not have the skills to do so. 

I wondered if there was an “official” release for windows, as for Arch Linux and Docker.

**Comment by schoerg** [comment]
Why not? Those are simple instructions.

**Comment by EffeF** [comment]
Not for me

**Comment by Darzlir** [comment]
nvllsvm, I do not know how I had not seen this thread. Sorry!!. So, would it be possible to see a version for windows?

Powershell simply closes with all versions, and I do not know how to patch it and build it :\

**Comment by Shidapu** [comment]
Would really like a Windows version available for download, as i don't know how to run this in Powershell.

**Comment by Darzlir** [comment]
nvllsvm, if there is not going to be a version for windows, a small guide on how to patch the file PluginSecurityManager.cs for authentic noob would be fine ...

Thank you very much anyway

**Comment by josephdouce** [comment]
Use docker, I run all my server apps on docker, makes everything much cleaner. At first, I thought it was a pain now I exclusively use docker.

**Comment by nihir** [comment]
a how-to on how to do this for Windows would be much appreciated too!

**Comment by 4oo4** [comment]
If you don't want to to to the trouble of setting up something like Cygwin or MinGW then TortoiseMerge is probably your best bet.

https://stackoverflow.com/questions/517257/how-do-i-apply-a-diff-patch-on-windows

**Comment by nvllsvm** [comment]
Not going to add this to this repo. Feel free to open a PR to ads a link if someone takes care of Windows builds
