### ISSUE TITLE
No Dashboard Notification Option

### ISSUE THREAD

**Issue by megapilot** [nvllsvm/emby-unlocked#12]
On web/notificationsettings.html one can usually set the notification types for various events.
Even with no further services installed, one should be able to select "Dashboard Notifications" in the "Use the following services:" menupoint: [see here](https://github.com/MediaBrowser/Wiki/wiki/images/server/notifications6.png)

With this fork only additionally installed services are shown and there is no menu point to control dashboard notifications.
I also only get dashboard notifications for events they are activated for by default.

**Comment by nvllsvm** [comment]
Compared the latest releases of emby-unlocked and emby. They have the same defaults on that screen.
