### ISSUE TITLE
DLNA not working with docker

### ISSUE THREAD

**Issue by Floflobel** [nvllsvm/emby-unlocked#13]
I installed the version that allows to have access bypass, thank you for your work.
However when I try to see my DLNA devices it does not seem to work because I am not in the same subnet.

Do you have a solution to work around this problem?

**Comment by zacharyrs** [comment]
How are you running emby? Via the docker image? If so, I think you neet --net=host for DLNA. 

It's not an issue with the image, as I run it fine. You probably haven't configured it correctly.

**Comment by nvllsvm** [comment]
Use ``--net=host``
