### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by flexbrane** [nvllsvm/emby-unlocked#14]
Hi,

I would like to compile an emby server docker image for linux, but using the official repository and this one for patches. But I doesn't understand yet how to compile and where to apply your patch.

Can you explain to me where you apply the patch and where you compile emby server (in your [dedicated repository](https://github.com/nvllsvm/docker-emby-unlocked) for exemple)?

Thanks a lot!

**Comment by Hippyjake** [comment]
Or a make file like I've asked for lol.

**Comment by nvllsvm** [comment]
The Arch Linux package is compiled like so: 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emby-server-unlocked

The Docker image builds and uses the Arch Linux package:
https://github.com/nvllsvm/docker-emby-unlocked

**Comment by nvllsvm** [comment]
Duplicate: https://github.com/nvllsvm/emby-unlocked/issues/7
