### ISSUE TITLE
[Guide] Android apk patch

### ISSUE THREAD

**Issue by Joern2410** [nvllsvm/emby-unlocked#15]
1. install apktool
sudo apt install apktool
2. download apk file
3. apktool d -r <name>.apk
4. sudo npm install -g js-beautify 
5. cd <name>/assets/www
6. js-beautify -r scripts/supporterkeypage.js
7. Download patches and apply: https://github.com/Joern2410/emby-android-patches

patch -N -p1 -r - scripts/supporterkeypage.js < ~/Downloads/supporterkeypage.patch

8. js-beautify -r bower_components/emby-apiclient/connectionmanager.js 
9. patch -N -p1 -r - bower_components/emby-apiclient/connectionmanager.js < ~/Downloads/connectionmanager.patch 
10. cd ./../..
11. apktool b <name> -o <name>.apk
12. Sign apk https://shatter-box.com/knowledgebase/android-apk-signing-tool-apk-signer/
13. copy apk signed and aligned to device, install and enjoy premier features

Worked for 2.9.67

**Comment by nvllsvm** [comment]
Neat and thanks. I won't be including this in the Emby Unlocked project since the result modified apk cannot be distributed legally. Cottect me if I'm wrong on that.

FYI - here's the latest source code of the app before going closed source.
https://github.com/nvllsvm/emby-android

**Comment by Joern2410** [comment]
Yes its no longer legal, because the app is closed source now.
But its not illegal to modify it, unless you are distribute the modified apk

**Comment by Iambecomeroot** [comment]
I followed all the instructions and I always get "App not installed" when I try to install it.
