### ISSUE TITLE
Why a patch instead of a proper fork?

### ISSUE THREAD

**Issue by alexknuckles** [nvllsvm/emby-unlocked#16]
They will fight this eventually. Why not just fork the last version before the paywalls started and debrand it, Iceweasel style? I think it would get a lot of support.

**Comment by nvllsvm** [comment]
I'm not a .NET Dev and don't have much of an interest in becoming one. This is the most maintainable solution for me.

If someone else had a well maintained fork, I'd discontinue this.

**Comment by skatastic** [comment]
Thanks friend
