### ISSUE TITLE
Fedora/CentOS release

### ISSUE THREAD

**Issue by robgjansen** [nvllsvm/emby-unlocked#17]
I've seen related issues #7, #9, and #14. I thought it could be useful to document a CentOS build.

**Comment by robgjansen** [comment]
So far I have the following, based on
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emby-server-unlocked

```
# install nux repo for ffmpeg
sudo rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
sudo rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
sudo yum install ffmpeg ffmpeg-devel

# install repo for mono
sudo yum install -y yum-utils
sudo rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
sudo yum-config-manager --add-repo http://download.mono-project.com/repo/centos7/
sudo yum install -y mono-complete
sudo yum install -y referenceassemblies-pcl

# other dependencies
sudo yum install ImageMagick ImageMagick-devel
sudo yum install sqlite sqlite-devel

# Emby
git clone https://github.com/nvllsvm/emby-unlocked
git clone https://github.com/MediaBrowser/Emby

cd Emby
sed 's/libMagickWand-6.Q8.so/libMagickWand-6.Q16HDRI.so/' -i MediaBrowser.Server.Mono/ImageMagickSharp.dll.config
patch -N -p1 -r - Emby.Server.Implementations/Security/PluginSecurityManager.cs < \
      ../emby-unlocked/patches/PluginSecurityManager.cs.patch

xbuild /p:Configuration='Release Mono' /p:Platform='Any CPU' /p:OutputPath="/home/user/Emby/build" /t:build MediaBrowser.sln
mono --aot='full' -O='all' /home/user/Emby/build/MediaBrowser.Server.Mono.exe

cp ../emby-unlocked/replacements/connectionmanager.js build/dashboard-ui/bower_components/emby-apiclient/connectionmanager.js
```

This outputs a bunch of files to `/home/user/Emby/build`, but I'm not sure what to do next. There is no `emby-server` in the build dir. Any pointers?

**Comment by AciDCooL** [comment]
Copy it to your existing emby folder:

`
mozroots --import --sync
echo "##Cleaning build##"
echo ""
echo ""
xbuild /p:Configuration="Release Mono" /p:Platform="Any CPU" /t:clean MediaBrowser.sln
echo "##Buildinggg##"
echo ""
echo ""
xbuild /p:Configuration="Release Mono" /p:Platform="Any CPU" /t:build MediaBrowser.sln

cp /opt/emby-unlocked/Emby-3.2.60.0/MediaBrowser.Server.Mono/bin/Release/* /opt/emby-server/bin/
`

**Comment by nvllsvm** [comment]
Outside of Docker, I won't accept distribution specific builds in this repo. I'd be happy to add links to the README if someone packages it.
