### ISSUE TITLE
Help: how do I access a library on a network share?

### ISSUE THREAD

**Issue by a8ree** [nvllsvm/emby-unlocked#20]
I'm running on Docker Toolbox / Windows 2012 R2 with HyperV. 

I cannot work out how to access my libraries on the network. 

Can someone give me a solution?

**Comment by tedr56** [comment]
This is a Emby issue, not really to post here
Since you use Docker, you need to set your network to "host", or IPs will be messed up.
And you need to mount your share locally, I would advice with automount (classic or systemd)

**Comment by nvllsvm** [comment]
Mount the share on the host and expose it to the container as a volume.
