### ISSUE TITLE
Need step by step tutorial

### ISSUE THREAD

**Issue by bheav** [nvllsvm/emby-unlocked#22]
Hello, I'm new to this and have been attempting to install Emby via Docker.  I did install Docker on my Windows 10 PC and it appears that I downloaded the image via Docker however when trying to use the sample commands to install all I get are errors.  My movies are on a separate drive (e:/Movies) and have no idea where the cache files are located.  I also don't know how to patch the original image to remove the nag screen.  Am I a hopeless case? 🤔
Thank you for reading
PS  Reading the forum someone pointed to a tutorial however the link does not work.

**Comment by nvllsvm** [comment]
Not sure how to help. Unfortunately, you need to familiarize youreself with Docker. If you need help with that, try /r/docker or a forum. 

The information on the Docker Hub for emby-unlocked should then be sufficient. https://hub.docker.com/r/nvllsvm/emby-unlocked/
