### ISSUE TITLE
Version 3.2.33.0 started getting ads again

### ISSUE THREAD

**Issue by deten** [nvllsvm/emby-unlocked#23]
Howdy,

I started getting ads again a little while back.  Web version shows 3.2.33.0

I will try to respond faster with any further information needed.

**Comment by nvllsvm** [comment]
Upgrade to 3.2.70.0 and let me know if you still have the problem.

**Comment by deten** [comment]
How do I do that?

**Comment by nvllsvm** [comment]
The latest version is always available using the `latest` Docker image tag.  You need to pull it (ex. `docker pull nvllsvm/emby-unlocked`).

**Comment by deten** [comment]
do I need to remake the container when I do this?

**Comment by nvllsvm** [comment]
No, the emby-unlocked Docker image is prebuilt.

**Comment by deten** [comment]
Okay, so I putty'd into synology.  sudo -i, ran the command.

It downloaded some stuff.

Then I restarted the container.

It still says I am running 3.2.33.0, did I miss a step?

**Comment by nvllsvm** [comment]
I'm not sure how to help you as I'm not familiar with Synology devices nor how you configured your image. 

If you're are still seeing ads after upgrading to the latest release, please open a new issue.

**Comment by deten** [comment]
The synology device really doesn't matter.  I am using docker and that is what drives the emby server.  My config was basically exactly what was described on the docker page.

I will try to find a real solution and post back with what I did for others.

**Comment by deten** [comment]
Long story short Docker containers will not update.  In order to update Docker Containers you need to delete and remake the container.
