### ISSUE TITLE
Motives

### ISSUE THREAD

**Issue by dnecto** [nvllsvm/emby-unlocked#25]
So what's the point of this now? The nag-screen's gone.

**Comment by nvllsvm** [comment]
Why not?

**Comment by nvllsvm** [comment]
Why not? :)

In all seriousness, I prefer running this patched version of Emby rather than the official. The upstream Docker image is _not_ fully open source as it uses their .NET Core build.

https://github.com/MediaBrowser/Emby/issues/3075

**Comment by nvllsvm** [comment]
I prefer running this patched version of Emby rather than the official. What started as an annoyance over a nagscreen grew into a major distrust as the Emby developers were often not very communicative regarding their intentions.

The upstream Docker images are no longer an option for me as they are not open source:

- The container's build scripts are non-existent.
- The .NET Core release of Emby is not open source.

See MediaBrowser/Emby#3075

**Comment by dnecto** [comment]
Okay, that's understandable.

But why continue to unlock the premium features? Surely you understand that starving the parent project of its funding will prove detrimental in the long run.

**Comment by nvllsvm** [comment]
emby-unlocked already exists, is maintainable, and has a stable build process. It does things better than the official release by not setting limitations on what is already there. If it causes the Emby project to suffer, then it would be only due to a failure to compete with the functionality emby-unlocked provides.

I just don't care how it impacts their project.

**Comment by dnecto** [comment]
> If it causes the Emby project to suffer, then it would be only due to a failure to compete with the functionality emby-unlocked provides.

What functionality? It's their functionality, you're just cracking it. Don't give yourself too much credit dude

> I just don't care how it impacts their project.

Glad we've got that point straight

> If they are suffering - compete with me by delivering something better.

How can they? You'll just steal it as quickly as they put it out 😂

**Comment by nvllsvm** [comment]
> What functionality? It's their functionality, you're just cracking it. Don't give yourself too much credit dude

Yes - they coded the functionality behind an artificial conditional statement. I removed it for a better user experience, that's all. 

> How can they? 

Make premium features proprietary plugins or make a new plugin entirely.

> You'll just steal it as quickly as they put it out joy

What I'm doing is not theft if they explicitly licensed this code to me and the rest of the world under the GPL.

**Comment by dnecto** [comment]
Alright mate, you keep telling yourself that. Whatever makes you sleep at night.

**Comment by Hippyjake** [comment]
Users don't like how an open source project is going, they can make changes. "Crack" it, play with it and try to take over the world with it. It's **open source**. The devs did that. They also ignore the user base, begging for someone to fork it.

Not to mention :kissing_heart: they don't point you here. You must go out of your way to find it.

"But it's the $number on Google search." Well. The devs should listen and act when users make a nose.

Just my nonsensical take on things.

**Comment by joshuaboniface** [comment]
"The devs are suffering"? Boo hoo. They're the ones who added a nag screen to a Free and Open Source project in an attempt to extort $100 payments from users, ignored those of us who cared, and supported a forum echo chamber of people who obviously have no clue how free software works (including yourself). They can get bent.

**Comment by hapylestat** [comment]
**many users here think that open source = free software, but it is wrong** point of view. Not talking about emby, but in general.

While, most likely, this fork doesn't breaking original license, those who use it should understand that:
- it is not supported, as ppl who forked it most likely r not a base project contributors and won't working on bug fixing and side effects of workaround
- may be not updated for a while
- not supported via forum of original product (i guess, as the code may be not identical and outdated)
- usage risks and another threads r totally on end-user responsibility 

By summarizing all this - it is complete user choose what to use and which project to support

PS. As project is OSS, anyone can write his own "premium" plugin alternative, but seems .. nobody looking for easy path ))
