### ISSUE TITLE
Would this work on a raspberry pi armf processor?

### ISSUE THREAD

**Issue by dannyspanish** [nvllsvm/emby-unlocked#29]
If it does work would someone be willing to let me a complete noobs guide to applying the patch? I've tried both docker and Arch Linux but struggle to get either of them to work with the instructions available.

Thanks.

**Comment by nvllsvm** [comment]
The AUR package has been updated to support any architecture. I have not tested it.
https://aur.archlinux.org/packages/emby-server-unlocked/
