### ISSUE TITLE
Not work for Ubuntu

### ISSUE THREAD

**Issue by xNobaBx** [nvllsvm/emby-unlocked#32]
Hi this thing doesnt work for ubuntu

**Comment by konstantinblaesi** [comment]
What are you talking about, this is a docker image...? This kind of report is 100% useless, because
* nobody knows what you did technically
* what errors/problems you encountered

**Comment by nvllsvm** [comment]
Ubuntu packages will not be added to this repo. I'd be happy to link to another repo if someone makes one for packages.
