### ISSUE TITLE
File permission Docker

### ISSUE THREAD

**Issue by xNobaBx** [nvllsvm/emby-unlocked#39]
Hi i cant add any media folder because lack of permission. iT says 
For Linux on Arch Linux, CentOS, Debian, Fedora, OpenSuse, or Ubuntu, you must grant the Emby system user at least read access to your storage locations.

So who is "Emby system user"  and how to grant the read access for it.

**Comment by nvllsvm** [comment]
Set the container's `PUID` and `PGID` environment variables to your the host's user that has access to your media folder.

```shell
$ docker run -e PUID=$(id -u) -e PGID=$(id -g) nvllsvm/emby-unlocked
```
