### ISSUE TITLE
[user error? no fault found now] help with running on RPI3

### ISSUE THREAD

**Issue by oliver-cfc** [nvllsvm/emby-unlocked#5]
O/S = archlinuxarm
I copied the PKGBUILD from AUR and added armv7h to the 'arch' array.  It compiled and installed OK but when starting I get this error

> [emby@rpi ~]$ mono /usr/lib/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe
> Info Main: Emby
> 	Command line: /usr/lib/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe
> 	Operating system: Unix 4.9.50.1
> 	64-Bit OS: False
> 	64-Bit Process: False
> 	Mono: 5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 18:27:31 UTC 2017)
> 	Processor count: 4
> 	Program data path: /var/lib/emby
> 	Application directory: /usr/lib/emby-server
> Error Main: Skia not available. Will try next image processor. libSkiaSharp.so
> Info ImageMagick: ImageMagick version: ImageMagick 6.9.9-13 Q16 armv7l 2017-09-13 http://www.imagemagick.org
> exception inside UnhandledException handler: Object reference not set to an instance of an object.
> 
> Info Main: Shutting down
> exception inside UnhandledException handler: Object reference not set to an instance of an object.
> 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
>   at MediaBrowser.Server.Mono.MainClass.Main (System.String[] args) [0x0009f] in <2f7ac2bbdaa745ca84b02e6f5e86a779>:0

The pkg provided by the distribution works OK so I'm assuming it's something in the patch or replacement file but I'm at a loss to work out what.

Any ideas?

**Comment by oliver-cfc** [comment]
Not sure what changed - maybe it was a result of clearing everything out and starting with the latest build but all is looking good now (and I found out I can use 'makepkg -A' rather than modifying the architecture array)

> $ pacman -Qi emby-server-unlocked
> Name            : emby-server-unlocked
> Version         : 3.2.32.0-1
> Description     : Emby Server compiled with a patch to unlock Emby Premiere features
> Architecture    : armv7h
> URL             : https://github.com/nvllsvm/emby-unlocked
> Licenses        : GPL2
> Groups          : None
> Provides        : emby-server
> Depends On      : ffmpeg  imagemagick  mono  referenceassemblies-pcl  sqlite
> Optional Deps   : None
> Required By     : None
> Optional For    : None
> Conflicts With  : None
> Replaces        : None
> Installed Size  : 25.92 MiB
> Packager        : Unknown Packager
> Build Date      : Mon 25 Sep 2017 11:25:54 PM UTC
> Install Date    : Mon 25 Sep 2017 11:28:50 PM UTC
> Install Reason  : Explicitly installed
> Install Script  : Yes
> Validated By    : None



> ● emby-server.service - Emby brings together your videos, music, photos, and live television.
>    Loaded: loaded (/usr/lib/systemd/system/emby-server.service; disabled; vendor preset: disabled)
>    Active: active (running) since Mon 2017-09-25 23:35:43 UTC; 5s ago
>  Main PID: 3942 (mono)
>     Tasks: 5 (limit: 4915)
>    CGroup: /system.slice/emby-server.service
>            └─3942 /usr/bin/mono /usr/lib/emby-server/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe

**Comment by zacharyrs** [comment]
If it all works fine, probably close the issue?

You can reopen it given the need later.

**Comment by oliver-cfc** [comment]
Closing issue as requested
