### ISSUE TITLE
How can I build Docker with this?  I am extremely newb

### ISSUE THREAD

**Issue by deten** [nvllsvm/emby-unlocked#6]
Hi Guys,

I have no clue how to get this working on Docker.  Any way someone can help me and put some steps together?

**Comment by BKPepe** [comment]
Hello,
I was doing it yesterday.

First you need download and install Docker ( https://docs.docker.com/engine/installation/ )

I use Docker Community Edition, which should be also enough for you.

For Ubuntu go here: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
For Debian go here:  https://docs.docker.com/engine/installation/linux/docker-ce/debian/

After you do 4. step in "Install Docker CE" , which is:  

> sudo docker run hello-world

Then you can go here and use the example (but you need to edit it to your's collect values:
https://github.com/nvllsvm/docker-emby-unlocked

It's very easy.

**Comment by zacharyrs** [comment]
If you don't mind not building it yourself, you can use the prebuilt image linked in the readme. There's a command there to get it running too.

**Comment by nvllsvm** [comment]
File an issue at the emby-unlocked Docker repo.
https://github.com/nvllsvm/docker-emby-unlocked

**Comment by deten** [comment]
Are you updating emby-unlocked Docker?  I started getting ads again.

**Comment by zacharyrs** [comment]
@deten
The docker build is automated (I think), and simply applies this patch before building.

I suspect you are facing ads due to using one of the apps that verify licenses themselves, as opposed to the web app hosted locally.

Also, this is technically a new issue.
