### ISSUE TITLE
make command

### ISSUE THREAD

**Issue by Hippyjake** [nvllsvm/emby-unlocked#7]
Im lazy, yes. Ha. But a make file would be killer. ive moved to Solus from Arch. The docker image works but feels slow.

**Comment by nvllsvm** [comment]
Look at how it's being built for the Docker image: https://github.com/nvllsvm/emby-unlocked/blob/master/docker/build.sh

I have no intentions of supporting a universal makefile, but would gladly link to a Solus package in the README if you made one.
