### ISSUE TITLE
Ubuntu release

### ISSUE THREAD

**Issue by Meiden-fc** [nvllsvm/emby-unlocked#9]
I've totally failed trying to make an Ubuntu build because I'm a absolutely noob.

Is there any chance that somebody could consider to make an Ubuntu Server pre-compiled version of this? It'd be very useful.

Thanks for this project.

**Comment by skatastic** [comment]
Just use docker.

**Comment by Meiden-fc** [comment]
Why should I use a "virtualized" program when the native one is available?

**Comment by skatastic** [comment]
Well the foremost reason is that it gives you exactly what you're asking for, an easy "installer" so you can be up and running with just a couple commands.  An extended reason is that docker isn't virtualizing anything, it merely contains a subsystem so there's nearly no overhead in running something on docker as opposed to bare metal.  Additionally running things in docker all but guarantee that updating something else won't end up breaking things you care about through some versioning problems.

**Comment by tankerkiller125** [comment]
The problem with running it on docker I have found though is DLNA simply doesn't work when emby is running in a container

**Comment by skatastic** [comment]
That's true only if you use the default network.  If you use host mode (not sure if I'm using the term correctly) then it works like normal.  That's how I have mine.

**Comment by tankerkiller125** [comment]
If I knew how to package emby myself I would write the script to create the deb file but unfortunately everytime I try to build emby it errors.

**Comment by nvllsvm** [comment]
Not adding dist packages to this repo. Feel free to open a PR to add a link to the README if someone takes care of it.
